Import('*')

# Add the test source files
GTest('uras.test', 'uras_test.cc')

# Add BTB test with minimal dependencies
GTest('btb.test', 
    'mockbtb.cc', 'btb.test.cc', '../stream_common.cc')

GTest('pbtb.test',
    'mockbtb.cc', 'pbtb.test.cc', '../stream_common.cc')

# Add TAGE test with necessary dependencies
GTest('tage.test', 
    'btb_tage.cc',
    'btb_tage.test.cc', 
    '../stream_common.cc',
    '../folded_hist.cc',
)

GTest('folded_hist.test',
    'folded_hist.test.cc',
    '../folded_hist.cc',
)

GTest('fetch_target_queue.test',
    'fetch_target_queue.test.cc',
)

# Add the test to UNITTESTS target
env.Append(UNITTESTS=['uras.test',
        'btb.test',
        'tage.test',
        'folded_hist.test',
        'fetch_target_queue.test'])
