name: gem5 Ideal BTB Performance Test

on:
  push:
    branches: [ xs-dev ]
  pull_request:
    branches: [ xs-dev ]

jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_v3_btb.sh
      benchmark_type: "spec06-0.8c"