name: gem5 vector Test

on:
  push:
    branches: [ xs-dev ]
  pull_request:
    branches: [ xs-dev ]

jobs:
  vector-test:
    runs-on: node
    continue-on-error: false
    name: XS-GEM5 - Running vector test
    steps:
      - uses: actions/checkout@v2
      - name: Build DRAMSim
        run: |
          export GEM5_HOME=$(pwd)
          cd ext/dramsim3
          git clone https://github.com/umd-memsys/DRAMsim3.git DRAMsim3
          cd DRAMsim3 && mkdir -p build
          cd build
          cmake ..
          make -j 48
          cd $GEM5_HOME
      - name: Build GEM5 opt
        run: |
          CC=gcc CXX=g++ scons build/RISCV/gem5.opt --linker=gold -j64
      - name: run vector test
        run: python3 .github/workflows/autotest/script/autotest.py -f .github/workflows/autotest/gem5-vec.cfg