name: gem5 Simple RVV Performance Test (Ideal BTB)

on:
  push:
    branches: [ xs-dev ]
  pull_request:
    branches: [ xs-dev ]

jobs:
  perf_test:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_v3_btb.sh
      benchmark_type: "spec06int-rvv-0.8c"
      vector_type: "simple"
      check_result: false # Warning: rvv test will not show the difftest failure