name: gem5 Ideal BTB Weekly Performance Test

on:
  schedule:
    # Run every Thursday at 23:59 UTC+8 (15:59 UTC)
    - cron: '59 15 * * 4'
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  perf_test_spec06:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_v3_btb.sh
      benchmark_type: "spec06-1.0c"
  
  perf_test_spec17:
    uses: ./.github/workflows/gem5-perf-template.yml
    with:
      script_path: ../kmh_v3_btb.sh
      benchmark_type: "spec17-1.0c" 